baseurl      = "https://yan1025.github.io/"
title        = "Yan"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "The meaning of life is to discover the true self"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "My new homepage or blog"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[languages.en]
title = "GodYan"
subtitle = "The meaning of life is to discover the true self"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "$ are you happy"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "life"
name       = "Life"
url        = "/life"
[[menu.main]]
identifier = "tech"
name       = "Tech"
url        = "/posts"

[[params.social]]
name = "github"
url = "https://github.com/Yan1025"

[[params.social]]
name = "email"
url = "mailto:13218057180@163.com"
